@FirstAidAPI_HostAddress = http://localhost:5085

# Get all events
GET {{FirstAidAPI_HostAddress}}/events
Accept: application/json

###

# Get event by ID
GET {{FirstAidAPI_HostAddress}}/events/1
Accept: application/json

###

# Get shifts for a specific event
GET {{FirstAidAPI_HostAddress}}/events/1/shifts