@FirstAidAPI_HostAddress = http://localhost:5085

# Get all events
GET {{FirstAidAPI_HostAddress}}/events
Accept: application/json

###

# Get all staff
GET {{FirstAidAPI_HostAddress}}/staff
Accept: application/json

###

# Create a new staff member
POST {{FirstAidAPI_HostAddress}}/staff
Content-Type: application/json

{
  "firstName": "Iris",
  "lastName": "Doe",
  "email": "iris.john@example.com",
  "phone": "+1234567890",
  "role": "FirstAider",
  "certificationLevel": "Basic",
  "certificationExpiry": "2025-12-01T00:00:00Z"
}

###

# Add staff to a shift
POST {{FirstAidAPI_HostAddress}}/shifts/1/staff/4

